server:
  port: 8080
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
rabbitmq:
  queueName: downloaded
  exchange: downloaded-exc
  routingKey: downloaded-rKey
resource-service:
  endpointHost: http://${RS_HOST:localhost}:8081/
song-service:
  endpointHost: http://${SS_HOST:localhost}:8082/
caller:
  maxRetries: 2
  backoff: 2000